/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.7 */

#include "schema.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(ACKNOWLEDGE, acknowledge_t, AUTO)


PB_BIND(PRESSURE_READING, pressure_reading_t, AUTO)


PB_BIND(IMU_READING, imu_reading_t, AUTO)


PB_BIND(TELEMETRY_PACKET, telemetry_packet_t, AUTO)


PB_BIND(FJALAR_DATA, fjalar_data_t, AUTO)


PB_BIND(FJALAR_MESSAGE, fjalar_message_t, AUTO)




